# Generated by Django 2.1.5 on 2019-03-02 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 5, 33, 4, 654710), verbose_name='date published'),
        ),
    ]
