# Generated by Django 2.1.5 on 2019-03-04 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190303_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_catagory', models.CharField(max_length=200)),
                ('catagory_summery', models.CharField(max_length=200)),
                ('catagory_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_series', models.CharField(max_length=200)),
                ('series_summery', models.CharField(max_length=200)),
                ('blog_catagory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BlogCatagory', verbose_name='Catagory')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 2, 54, 7, 950479), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BlogSeries', verbose_name='Series'),
        ),
    ]
